---
title:    "Risk of Business Failure - Pre-Process Question A, A.ctd, B"
students: F.Gemignani, S.Cucchi, F.Falleni
output:   aida-preprocess.nb.html
---

Libraries
```{r}
# install.packages("sjmisc")
# devtools::install_github("ropensci/skimr")

library(skimr)       
library(ggplot2)      
library(hrbrthemes)   
library(forcats)      
library(plyr)        
```

Import & Setup AIDA dataset
```{r}
# clean all
rm(list=ls())

# working dir
wdir_fg = "/Users/francescogemignani/Google Drive/SMD/_Risk-of-business-failure/git"
wdir_ff = "C:/Users/falle/OneDrive - University of Pisa/Data Science/Statistical Methods for Data Science/smdproject2021"
wdir_sc = "/Users/samuele/University/2.SMD/Risk-of-Business-Failure"
setwd(wdir_fg)

# import aida dataset
load(file="../aida.RData")

# For each attribute name, replace all white space whit dot symbol
colnames(aida) <- gsub(" ",".",colnames(aida))
```

Summary
```{r}
skim(aida)
```

Failed
```{r}
# Add 'Failed' feature to AIDA dataset. It describe if a company is failed or not regardless of the cause. In particular a company with Legal status no active has marked with Failed = Yes,,
# otherwise Failed = No when has labeled as Active.

# Missing values don't occour
aida[is.na(aida$Legal.status),]

# Table of Legal status
table(aida$Legal.status)*100/nrow(aida)

# Make the operator
'%!in%' <- function(x,y)!('%in%'(x,y))

# Add new empty column
aida$Failed <- NULL

# For each 'Legal status' which contains 'Active' substring fill in new column 'No' else 'Yes'
act_vector <- c('Active','Active (default of payments)','Active (receivership)')
aida[aida$Legal.status %in% act_vector,'Failed'] <- 'No'
aida[aida$Legal.status %!in% act_vector,'Failed'] <- 'Yes'

aida[is.na(aida$Failed), ]
aida$Failed <- as.factor(aida$Failed)

# Failed info
table(aida$Failed)*100/nrow(aida)
```

ATECO.Sector.Name
```{r}
# Add a column with the respective ISTAT sector of the company. In particular first two digits of ATECO 2007code identify the company sector which is an upper case character that began to [A-U] alphabetical range.

#Delete record with ADECO code null (18327)
aida <- aida[!is.na(aida$ATECO.2007code),]

# Add the attribute 'ATECO.Sector.Code' which contain the characters of the sector identified by the first two ATECO 2007 code digits.
aida$ATECO.Sector.Code <- NULL
aida$ATECO.Sector.Code <- substr(aida$ATECO.2007code, 0, 2)

# Make a dataframe called istat.sectors.map, which contains two features:
# 1. ATECO.Sector.Code: first two digits of 'ATECO 2007code'
# 2. ATECO.Sector.Name: the respective sector name of that ATECO.Sector.Code
# Istat sectors can be found in https://www.istat.it/it/archivio/17888

ATECO.Sector.Code <- c('01', '02', '03', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '35', '36', '37', '38', '39', '41', '42', '43', '45', '46', '47', '49', '50', '51', '52', '53', '55', '56', '58', '59', '60', '61', '62', '63', '64', '65', '66', '68', '69', '70', '71', '72', '73', '74', '75', '77', '78', '79', '80', '81', '82', '84', '85', '86', '87', '88', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '00')

ATECO.Sector.Name <- c('A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'E', 'E', 'E', 'E', 'F', 'F', 'F', 'G', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'I', 'I', 'J', 'J', 'J', 'J', 'J', 'J', 'K', 'K', 'K', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'P', 'Q', 'Q', 'Q', 'R', 'R', 'R', 'R', 'S', 'S', 'S', 'T', 'T','U', 'no.sector')

ATECO.Sector.Description <- c('AGRICOLTURA, SILVICOLTURA E PESCA', 'AGRICOLTURA, SILVICOLTURA E PESCA', 'AGRICOLTURA, SILVICOLTURA E PESCA','ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'FORNITURA DI ENERGIA ELETTRICA, GAS, VAPORE E ARIA CONDIZIONATA', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'COSTRUZIONI', 'COSTRUZIONI', 'COSTRUZIONI', 'COMMERCIO ALL INGROSSO E AL DETTAGLIO; RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI', 'COMMERCIO ALL INGROSSO E AL DETTAGLIO; RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI', 'COMMERCIO ALL INGROSSO E AL DETTAGLIO; RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'ATTIVITÀ DEI SERVIZI DI ALLOGGIO E DI RISTORAZIONE', 'ATTIVITÀ DEI SERVIZI DI ALLOGGIO E DI RISTORAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'ATTIVITÀ FINANZIARIE E ASSICURATIVE', 'ATTIVITÀ FINANZIARIE E ASSICURATIVE', 'ATTIVITÀ FINANZIARIE E ASSICURATIVE', 'ATTIVITÀ IMMOBILIARI', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'AMMINISTRAZIONE PUBBLICA E DIFESA; ASSICURAZIONE SOCIALE OBBLIGATORIA', 'ISTRUZIONE', 'SANITÀ E ASSISTENZA SOCIALE', 'SANITÀ E ASSISTENZA SOCIALE', 'SANITÀ E ASSISTENZA SOCIALE', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ALTRE ATTIVITÀ DI SERVIZI', 'ALTRE ATTIVITÀ DI SERVIZI', 'ALTRE ATTIVITÀ DI SERVIZI', 'ATTIVITÀ DI FAMIGLIE E CONVIVENZE COME DATORI DI LAVORO PER PERSONALE DOMESTICO', 'ATTIVITÀ DI FAMIGLIE E CONVIVENZE COME DATORI DI LAVORO PER PERSONALE DOMESTICO','ORGANIZZAZIONI ED ORGANISMI EXTRATERRITORIALI', 'no.sector')

istat.sectors.map <- data.frame(ATECO.Sector.Code=ATECO.Sector.Code, ATECO.Sector.Name=ATECO.Sector.Name, ATECO.Sector.Description=ATECO.Sector.Description)

# Merge istat.sectors.map with AIDA dataframe, by ATECO.Sector.Code key
aida <- merge(aida,istat.sectors.map,by="ATECO.Sector.Code")

# Delete ATECO.Sector.Code feature, because we already have the secor name.
aida$ATECO.Sector.Code <- NULL

# Cast ATECO.Sector.Name as Factor
aida$ATECO.Sector.Name <- as.factor(aida$ATECO.Sector.Name)

rm(istat.sectors.map)
# Description of ISTAT sectors
# https://www.istat.it/it/archivio/17888
# http://www.fr.camcom.gov.it/sites/default/files/cciaa/RinnovoConsiglio/ateco-2007-struttura.pdf
```

Legal Form
```{r}
# Remove missing values
aida <- aida[!is.na(aida$Legal.form),]
```

Legal Status by Failed
```{r}
table(aida$Failed)*100/nrow(aida)

ggplot(data=aida, aes(x=Failed, fill=Legal.status)) +
  geom_bar() +
  scale_fill_hue(c = 90) 
```

Legal Form by Failed
```{r}
table(aida$Failed)*100/nrow(aida)

ggplot(data=aida, aes(x=Failed, fill=Legal.form)) +
  geom_bar() +
  scale_fill_hue(c = 90) 
```

Legal Status Bar Plot
```{r}
table(aida$Legal.status)*100/nrow(aida)

ggplot(data=aida, aes(x=fct_rev(fct_infreq(Legal.status)), fill=Legal.status)) +
  geom_bar() +
  scale_fill_hue(c = 40) +
  theme(legend.position="none") + 
  coord_flip()
```

Legal Form Bar Plot
```{r}
table(aida$Legal.form)*100/nrow(aida)

ggplot(data=aida, aes(x=fct_rev(fct_infreq(Legal.form)), fill=Legal.form)) +
  geom_bar() +
  scale_fill_hue(c = 40) +
  theme(legend.position="none") + 
  coord_flip()
```

Age
```{r}
# The company age is defined as as the difference between Incorporation.year and Last.accounting.closing.date
aida.age <- aida

# Handle Incorporation.year: missing values occour
summary(aida.age$Incorporation.year)

# Handle Last.accounting.closing.date:  no missing values
summary(aida.age$Last.accounting.closing.date)
table(aida.age$Last.accounting.closing.date)

# Print the median for each sector of Incorporation.year
tapply(aida.age$Incorporation.year,aida.age$ATECO.Sector.Name,median, na.rm=TRUE)

# For each ATECO.Sector.Name group replace the 'Incorporation year' nan value with the respective median. In this way the result is more accurate than computing the median on entire Incorporation.year values.
compute.median <- function(x) replace(x, is.na(x), median(x, na.rm = TRUE))
aida.age <- ddply(aida.age,~ATECO.Sector.Name,transform, Incorporation.year = compute.median(`Incorporation.year`))

# Compute 'Age' attribute
aida.age$Age <- aida.age$Last.accounting.closing.date - aida.age$Incorporation.year
aida.age$Age <- as.integer(aida.age$Age)
```
```{r}
# Anomalies

# There are some company with negative age, with Incorporation year greater then Last accounting closing date. We suppose that are digit error. Therefore we remove all that records
summary(aida.age$Age)
head(aida.age[aida.age$Age > 35.5,c('Age','Last.accounting.closing.date','Incorporation.year')])

# Remove negative ages
aida.age <- aida.age[aida.age$Age >= 0,]

# Age Anomaly Detection: iqr range approach
iqr <- IQR(aida.age$Age)
q1 <- quantile(aida.age$Age,0.25)
q3 <- quantile(aida.age$Age,0.75)
lower.whisker <- q1 - 1.5*iqr
upper.whisker <- q3 + 1.5*iqr

outliers <- aida.age[aida.age$Age < lower.whisker | aida.age$Age > upper.whisker,'Age']
table(outliers)

boxplot(aida.age$Age)
# We decided to don't remove outliers because are not error/noise but companies with higher age. The boxplot shows that the age between the median and the maximum age is sparse.

# export aida.age 
aida.age <- aida.age[,c('Age','Legal.form','ATECO.Sector.Name','Registered.office.address...Region','Last.accounting.closing.date','Failed')]
skim(aida.age)
save(aida.age, file="./dataset/aida.age.RData") # R binary format
rm(aida.age)
```

Size
```{r}
# Il legislatore attribuisce la dimensione di un'azienda in base al totale degli elementi che costituiscono l'attivo dello stato patrimoniale, al risultato di esercizio ed al numero di dipendenti. Nel nostro caso abbiamo deciso di attribuire a size il totale delle attività dello sp, in particolare abbiamo considerato il totale degli assets nell'ultimo anno disponibile per esprimere il valore  degli impieghi di un'azienda. 
aida.size <- aida

# We consider all the company without nan value in total assets last available.
aida.size <- aida.size[!is.na(aida.size$Total.assetsth.EURLast.avail..yr),]
summary(aida.size$Total.assetsth.EURLast.avail..yr)
```
```{r}
# Anomaly detection

# Before outliers detection
boxplot(aida.size$Total.assetsth.EURLast.avail..yr)
plot(density(aida.size$Total.assetsth.EURLast.avail..yr))

# Size Anomaly Detection: iqr range approach
iqr <- IQR(aida.size$Total.assetsth.EURLast.avail..yr)
q1 <- quantile(aida.size$Total.assetsth.EURLast.avail..yr,0.25)
q3 <- quantile(aida.size$Total.assetsth.EURLast.avail..yr,0.75)
lower.whisker <- q1 - 1.5*iqr
upper.whisker <- q3 + 1.5*iqr

# Remove all outliers not between [q1-1.5*iqr,q3+1.5*iqr] (external from two whiskers)
aida.size <- aida.size[aida.size$Total.assetsth.EURLast.avail..yr >= lower.whisker & aida.size$Total.assetsth.EURLast.avail..yr <= upper.whisker,]

#After outliers detection
boxplot(aida.size$Total.assetsth.EURLast.avail..yr)
plot(density(aida.size$Total.assetsth.EURLast.avail..yr))

# export aida.size 
aida.size <- aida.size[,c('Total.assetsth.EURLast.avail..yr','Legal.form','ATECO.Sector.Name','Registered.office.address.-.Region','Last.accounting.closing.date','Failed')]
skim(aida.size)
save(aida.size, file="./dataset/aida.size.RData") # R binary format
rm(aida.size)
```

ROI: Return on Investments
```{r}
# Take all that companies which report ROI of last available year. Obviously all missing values are been deleted. The dataset is composed by 735.268 companies (39.20%)
aida.roi <- aida

b<- nrow(aida.roi)
aida.roi <- aida.roi[!is.na(aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr'),]
a <- nrow(aida.roi)
ratio <- a*100/b

summary(aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr')
```
```{r}
# ROI Anomaly Detection: iqr range approach
iqr <- IQR(aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr')
q1 <- quantile(aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr',0.25)
q3 <- quantile(aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr',0.75)
lower.whisker <- q1 - 1.5*iqr
upper.whisker <- q3 + 1.5*iqr

outliers <- aida.roi[aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr' < lower.whisker | 
                     aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr' > upper.whisker,c('Return.on.investment.(ROI).(%)%Last.avail..yr')]
#table(outliers)
boxplot(aida.roi$'Return.on.investment.(ROI).(%)%Last.avail..yr')

# The outliers are companies with the higher and lower roi. We don't remove these record because the roi dataset composed only from 20.61% of record and could be usefull.

# export aida.roi 
aida.roi <- aida.roi[,c('Return.on.investment.(ROI).(%)%Last.avail..yr','Legal.form','ATECO.Sector.Name','Registered.office.address.-.Region','Last.accounting.closing.date','Failed')]
skim(aida.roi)
save(aida.roi, file="./dataset/aida.roi.RData") # R binary format
```
