---
title: "aida-yearpreprocess"
description: "script to generate the dataset with the absolute years"
students: F.Gemignani, S.Cucchi, F.Falleni
output: html_notebook
---

```{r}
#install.packages("data.table") 
library(data.table)
```

Import & Setup AIDA dataset
```{r}
# clean all
rm(list=ls())

# working dir
wdir_fg = "/Users/francescogemignani/Google Drive/SMD/_Risk-of-business-failure/git"
wdir_ff = "C:/Users/falle/Documents/GitHub/Risk-of-Business-Failure"
wdir_sc = "/Users/samuele/University/2.SMD/Risk-of-Business-Failure"
setwd(wdir_ff)

# import aida dataset
load(file="aida.RData")

# For each attribute name, replace all white space whit dot symbol
colnames(aida) <- gsub(" ",".",colnames(aida))
```

Per ogni record del dataframe, vengono creati tre record:
  - uno con i campi relativi all'anno corrente (Last.avail)
  - uno con i campi relativi all'anno precedente (-1)
  - uno con i campi relativi a due anni precedenti (-2)
```{r}
list = list()

i=1

for (row in 1:nrow(aida)){
  aida.row = aida[row,]
  
  last.year = aida.row["Last.accounting.closing.date"]
  ateco.code = aida.row["ATECO.2007code"]
  legal.form = aida.row["Legal.form"]
  legal.status = aida.row["Legal.status"]
  province = aida.row["Province"]
  comune = aida.row["Registered.office.address.-.Commune.ISTAT.code"]
  regione = aida.row["Registered.office.address.-.Region"]
  company.name = aida.row["Company.name"]
  file = aida.row["File"]
  tax.code = aida.row["Tax.code.number"]
  incorporation.year = aida.row["Incorporation.year"]
  
 list[[i]] <- c(last.year,
                incorporation.year,
                company.name,
                file,
                tax.code,
                ateco.code,
                legal.form,
                legal.status,
                province,
                comune,
                regione,
                aida.row["Banks/turnover%Last.avail..yr"],
                aida.row["Cash.Flowth.EURLast.avail..yr"],
                aida.row["Cost.of.debit.(%)%Last.avail..yr"],
                aida.row["Current.liabilities/Tot.ass.%Last.avail..yr"],
                aida.row["Current.ratioLast.avail..yr"],
                aida.row["Debt/EBITDA.ratio%Last.avail..yr"],
                aida.row["Debt/equity.ratio%Last.avail..yr"],
                aida.row["EBITDA/Vendite%Last.avail..yr"],
                aida.row["EBITDAth.EURLast.avail..yr"],
                aida.row["Interest/Turnover.(%)%Last.avail..yr"],
                aida.row["LeverageLast.avail..yr"],
                aida.row["Liquidity.ratioLast.avail..yr"],
                aida.row["Net.financial.positionth.EURLast.avail..yr"],
                aida.row["Net.working.capitalth.EURLast.avail..yr"],
                aida.row["Number.of.employeesLast.avail..yr"],
                aida.row["Profit.(loss)th.EURLast.avail..yr"],
                aida.row["Return.on.asset.(ROA)%Last.avail..yr"],
                aida.row["Return.on.equity.(ROE)%Last.avail..yr"],
                aida.row["Return.on.investment.(ROI).(%)%Last.avail..yr"],
                aida.row["Return.on.sales.(ROS)%Last.avail..yr"],
                aida.row["Solvency.ratio.(%)%Last.avail..yr"],
                aida.row["Total.assets.turnover.(times)Last.avail..yr"],
                aida.row["Total.assetsth.EURLast.avail..yr"])
 
 i=i+1;
 
 list[[i]] <- c(last.year-1,
                incorporation.year,
                company.name,
                file,
                tax.code,
                ateco.code,
                legal.form,
                legal.status,
                province,
                comune,
                regione,
                aida.row["Banks/turnover%Year.-.1"],
                aida.row["Cash.Flowth.EURYear.-.1"],
                aida.row["Cost.of.debit.(%)%Year.-.1"],
                aida.row["Current.liabilities/Tot.ass.%Year.-.1"],
                aida.row["Current.ratioYear.-.1"],
                aida.row["Debt/EBITDA.ratio%Year.-.1"],
                aida.row["Debt/equity.ratio%Year.-.1"],
                aida.row["EBITDA/Vendite%Year.-.1"],
                aida.row["EBITDAth.EURYear.-.1"],
                aida.row["Interest/Turnover.(%)%Year.-.1"],
                aida.row["LeverageYear.-.1"],
                aida.row["Liquidity.ratioYear.-.1"],
                aida.row["Net.financial.positionth.EURYear.-.1"],
                aida.row["Net.working.capitalth.EURYear.-.1"],
                aida.row["Number.of.employeesYear.-.1"],
                aida.row["Profit.(loss)th.EURYear.-.1"],
                aida.row["Return.on.asset.(ROA)%Year.-.1"],
                aida.row["Return.on.equity.(ROE)%Year.-.1"],
                aida.row["Return.on.investment.(ROI).(%)%Year.-.1"],
                aida.row["Return.on.sales.(ROS)%Year.-.1"],
                aida.row["Solvency.ratio.(%)%Year.-.1"],
                aida.row["Total.assets.turnover.(times)Year.-.1"],
                aida.row["Total.assetsth.EURYear.-.1"]
                )

 i=i+1
 
  list[[i]] = c(last.year-2,
                incorporation.year,
                company.name,
                file,
                tax.code,
                ateco.code,
                legal.form,
                legal.status,
                province,
                comune,
                regione,
                aida.row["Banks/turnover%Year.-.2"],
                aida.row["Cash.Flowth.EURYear.-.2"],
                aida.row["Cost.of.debit.(%)%Year.-.2"],
                aida.row["Current.liabilities/Tot.ass.%Year.-.2"],
                aida.row["Current.ratioYear.-.2"],
                aida.row["Debt/EBITDA.ratio%Year.-.2"],
                aida.row["Debt/equity.ratio%Year.-.2"],
                aida.row["EBITDA/Vendite%Year.-.2"],
                aida.row["EBITDAth.EURYear.-.2"],
                aida.row["Interest/Turnover.(%)%Year.-.2"],
                aida.row["LeverageYear.-.2"],
                aida.row["Liquidity.ratioYear.-.2"],
                aida.row["Net.financial.positionth.EURYear.-.2"],
                aida.row["Net.working.capitalth.EURYear.-.2"],
                aida.row["Number.of.employeesYear.-.2"],
                aida.row["Profit.(loss)th.EURYear.-.2"],
                aida.row["Return.on.asset.(ROA)%Year.-.2"],
                aida.row["Return.on.equity.(ROE)%Year.-.2"],
                aida.row["Return.on.investment.(ROI).(%)%Year.-.2"],
                aida.row["Return.on.sales.(ROS)%Year.-.2"],
                aida.row["Solvency.ratio.(%)%Year.-.2"],
                aida.row["Total.assets.turnover.(times)Year.-.2"],
                aida.row["Total.assetsth.EURYear.-.2"]
                )
  
  i=i+1
 
  if(row %% 1000 == 0)
    print(row)

}
```


```{r}
new.aida <- rbindlist(list, use.names=FALSE)
colnames(new.aida) = c("Year",
                 "Incorporation.year",
                 "Company.name",
                 "File",
                 "Tax.code.number",
                 "ATECO.2007code",
                 "Legal.form",
                 "Legal.status",
                 "Province",
                 "Comune.ISTAT.code",
                 "Region",
                 "Banks/turnover",
                 "Cash.Flowth",
                 "Cost.of.debit",
                 "Current.liabilities/Tot.ass",
                 "Current.ratio",
                 "Debt/EBITDA.ratio",
                 "Debt/equity.ratio",
                 "EBITDA/Vendite",
                 "EBITDAth",
                 "Interest/Turnover",
                 "Leverage",
                 "Liquidity.ratio",
                 "Net.financial.positionth",
                 "Net.working.capitalth",
                 "Number.of.employees",
                 "Profit.(loss)th",
                 "ROA",
                 "ROE",
                 "ROI",
                 "ROS",
                 "Solvency.ratio",
                 "Total.assets.turnover.(times)",
                 "Total.assetsth"
                 )
```

```{r}
fwrite(new.aida, "aida_preproc.csv")
```


