---
title:    "Risk of Business Failure - Pre-Process Question A, A.ctd, B"
students: F.Gemignani, S.Cucchi, F.Falleni
output:   aida-preprocess.nb.html
---

Libraries
```{r}
# install.packages("sjmisc")
# devtools::install_github("ropensci/skimr")
#install.packages("tidyverse")
library(tidyverse)
library(viridis)
library(data.table)
library(skimr)       
library(ggplot2)      
library(hrbrthemes)   
library(forcats)      
library(plyr)        
```

Import & Setup AIDA dataset
```{r}
# import aida dataset
rm(list=ls())
aida.abs.path <- "./dataset/aida_abs.csv"
df <- fread(aida.abs.path)

# For each attribute name, replace all white space whit dot symbol
colnames(df) <- gsub(" ",".",colnames(df))
colnames(df)
```

Tipizzazione delle features
```{r}
# L'assolutizzazione del dataset ha fatto perdere i tipi di alcune features, quindi li ripristino esattamente come sono nel
# dataset aida che ci è stato fornito

# I null values di Legal form sono stati convertiti in empty string, quindi li risetto come null values
df[df$Legal.form == "",c('Legal.form')] <- NA

# Variabili factor
df$Legal.form <- as.factor(df$Legal.form)
df$Legal.status <- as.factor(df$Legal.status)
df$Province <- as.factor(df$Province)
df$Comune.ISTAT.code <- as.factor(df$Comune.ISTAT.code)
df$Region <- as.factor(df$Region)

# Variabili di tipo character
df$ATECO.2007code <- as.character(df$ATECO.2007code)
df$Company.name <- as.character(df$Company.name)
df$Tax.code.number <- as.character(df$Tax.code.number)
df$File <- as.character(df$File)

#Aida Sector name Correction
to.modify5=nchar(as.character(df$ATECO.2007code))==5
to.modify1=nchar(as.character(df$ATECO.2007code))==1
df[to.modify1]$ATECO.2007code = sub("^", "000000", df[to.modify1]$ATECO.2007code)
df[to.modify5]$ATECO.2007code = sub("^", "0", df[to.modify5]$ATECO.2007code)
```

Summary
```{r}
skim(df)
```

Failed
```{r}
# Aggiungo la variabile 'Failed' al dataframe. La variabile indica se un'azienda è fallita o no, indipendentemente dalla causa. In particolare, un'impresa con Legal status 'no active' (sottostringa) viene etichettata con Failed=Yes, altrimenti Failed=No.

# Controllo che legal status non abbia null values
df[is.na(df$Legal.status),]

# Table di Legal status
table(df$Legal.status)*100/nrow(df)

# Creo l'operatore
'%!in%' <- function(x,y)!('%in%'(x,y))

# Aggiungo la feature vuota
df$Failed <- NULL

# Per ogni'Legal status' che contiene 'Active' come substring etichetto la variabile 'Failed' come 'No', altrimenti 'Yes'
act_vector <- c('Active','Active (default of payments)','Active (receivership)')
df[df$Legal.status %in% act_vector,'Failed'] <- 'No'
df[df$Legal.status %!in% act_vector,'Failed'] <- 'Yes'

# Setto la variabile come factor
df$Failed <- as.factor(df$Failed)

# Table di Failed (% - ratio)
table(df$Failed)*100/nrow(df)
```

ATECO.Sector.Name
```{r}
# Add a column with the respective ISTAT sector of the company. In particular first two digits of ATECO 2007code identify the company sector which is an upper case character that began to [A-U] alphabetical range.

#Delete record with ATECO code null
df <- df[!is.na(df$ATECO.2007code),]

# Add the attribute 'ATECO.Sector.Code' which contain the characters of the sector identified by the first two ATECO 2007 code digits.
df$ATECO.Sector.Code <- NULL
df$ATECO.Sector.Code <- substr(df$ATECO.2007code, 0, 2)

# Make a dataframe called istat.sectors.map, which contains two features:
# 1. ATECO.Sector.Code: first two digits of 'ATECO 2007code'
# 2. ATECO.Sector.Name: the respective sector name of that ATECO.Sector.Code
# Istat sectors can be found in https://www.istat.it/it/archivio/17888

ATECO.Sector.Code <- c('01', '02', '03', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '35', '36', '37', '38', '39', '41', '42', '43', '45', '46', '47', '49', '50', '51', '52', '53', '55', '56', '58', '59', '60', '61', '62', '63', '64', '65', '66', '68', '69', '70', '71', '72', '73', '74', '75', '77', '78', '79', '80', '81', '82', '84', '85', '86', '87', '88', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '00')

ATECO.Sector.Name <- c('A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'E', 'E', 'E', 'E', 'F', 'F', 'F', 'G', 'G', 'G', 'H', 'H', 'H', 'H', 'H', 'I', 'I', 'J', 'J', 'J', 'J', 'J', 'J', 'K', 'K', 'K', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'P', 'Q', 'Q', 'Q', 'R', 'R', 'R', 'R', 'S', 'S', 'S', 'T', 'T','U', 'no.sector')

ATECO.Sector.Description <- c('AGRICOLTURA, SILVICOLTURA E PESCA', 'AGRICOLTURA, SILVICOLTURA E PESCA', 'AGRICOLTURA, SILVICOLTURA E PESCA','ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ESTRAZIONE DI MINERALI DA CAVE E MINIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'ATTIVITÀ MANIFATTURIERE', 'FORNITURA DI ENERGIA ELETTRICA, GAS, VAPORE E ARIA CONDIZIONATA', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'FORNITURA DI ACQUA; RETI FOGNARIE, ATTIVITÀ DI GESTIONE DEI RIFIUTI E RISANAMENTO', 'COSTRUZIONI', 'COSTRUZIONI', 'COSTRUZIONI', 'COMMERCIO ALL INGROSSO E AL DETTAGLIO; RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI', 'COMMERCIO ALL INGROSSO E AL DETTAGLIO; RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI', 'COMMERCIO ALL INGROSSO E AL DETTAGLIO; RIPARAZIONE DI AUTOVEICOLI E MOTOCICLI', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'TRASPORTO E MAGAZZINAGGIO', 'ATTIVITÀ DEI SERVIZI DI ALLOGGIO E DI RISTORAZIONE', 'ATTIVITÀ DEI SERVIZI DI ALLOGGIO E DI RISTORAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'SERVIZI DI INFORMAZIONE E COMUNICAZIONE', 'ATTIVITÀ FINANZIARIE E ASSICURATIVE', 'ATTIVITÀ FINANZIARIE E ASSICURATIVE', 'ATTIVITÀ FINANZIARIE E ASSICURATIVE', 'ATTIVITÀ IMMOBILIARI', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'ATTIVITÀ PROFESSIONALI, SCIENTIFICHE E TECNICHE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'NOLEGGIO, AGENZIE DI VIAGGIO, SERVIZI DI SUPPORTO ALLE IMPRESE', 'AMMINISTRAZIONE PUBBLICA E DIFESA; ASSICURAZIONE SOCIALE OBBLIGATORIA', 'ISTRUZIONE', 'SANITÀ E ASSISTENZA SOCIALE', 'SANITÀ E ASSISTENZA SOCIALE', 'SANITÀ E ASSISTENZA SOCIALE', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ATTIVITÀ ARTISTICHE, SPORTIVE, DI INTRATTENIMENTO E DIVERTIMENTO', 'ALTRE ATTIVITÀ DI SERVIZI', 'ALTRE ATTIVITÀ DI SERVIZI', 'ALTRE ATTIVITÀ DI SERVIZI', 'ATTIVITÀ DI FAMIGLIE E CONVIVENZE COME DATORI DI LAVORO PER PERSONALE DOMESTICO', 'ATTIVITÀ DI FAMIGLIE E CONVIVENZE COME DATORI DI LAVORO PER PERSONALE DOMESTICO','ORGANIZZAZIONI ED ORGANISMI EXTRATERRITORIALI', 'no.sector')

istat.sectors.map <- data.frame(ATECO.Sector.Code=ATECO.Sector.Code, ATECO.Sector.Name=ATECO.Sector.Name, ATECO.Sector.Description=ATECO.Sector.Description)

# Merge istat.sectors.map with df dataframe, by ATECO.Sector.Code key
df <- merge(df,istat.sectors.map,by="ATECO.Sector.Code")

# Delete ATECO.Sector.Code feature, because we already have the secor name.
df$ATECO.Sector.Code <- NULL

# Cast ATECO.Sector.Name as Factor
df$ATECO.Sector.Name <- as.factor(df$ATECO.Sector.Name)
rm(istat.sectors.map)
# Description of ISTAT sectors
# https://www.istat.it/it/archivio/17888
# http://www.fr.camcom.gov.it/sites/default/files/cciaa/RinnovoConsiglio/ateco-2007-struttura.pdf

table(df$ATECO.Sector.Name)
```

Legal Form
```{r}
# Elimino le aziende che non specificano legal.form
nrow(df[is.na(df$Legal.form),])/nrow(df)*100
df <- df[!is.na(df$Legal.form),]

```

Age
```{r}
# The company age is defined as as the difference between Incorporation.year and Last.accounting.closing.date
aida.age <- df

# Handle Incorporation.year: missing values occour
summary(aida.age$Incorporation.year)

# Print the median for each sector of Incorporation.year
tapply(aida.age$Incorporation.year,aida.age$ATECO.Sector.Name,median, na.rm=TRUE)

# For each ATECO.Sector.Name group replace the 'Incorporation year' nan value with the respective median. In this way the result is more accurate than computing the median on entire Incorporation.year values.
compute.median <- function(x) replace(x, is.na(x), median(x, na.rm = TRUE))
aida.age <- ddply(aida.age,~ATECO.Sector.Name,transform, Incorporation.year = compute.median(`Incorporation.year`))

# Creo la variabile 'Age'. L'età dell'azienda è relativa (ie. considero l'età dell'azienda in un determinato anno)
aida.age$Age <- aida.age$Year - aida.age$Incorporation.year
aida.age$Age <- as.integer(aida.age$Age)
```

```{r}
# Anomalies

# There are some company with negative age. Therefore we remove all that records
summary(aida.age$Age)

head(aida.age[aida.age$Age > 35.5,c('Age','Year','Incorporation.year')])

# Remove negative ages
aida.age <- aida.age[aida.age$Age >= 0,]

# Age Anomaly Detection: iqr range approach
iqr <- IQR(aida.age$Age)
q1 <- quantile(aida.age$Age,0.25)
q3 <- quantile(aida.age$Age,0.75)
lower.whisker <- q1 - 1.5*iqr
upper.whisker <- q3 + 1.5*iqr

outliers <- aida.age[aida.age$Age < lower.whisker | aida.age$Age > upper.whisker,'Age']
table(outliers)
nrow(aida.age)/length(outliers)

# We decided to don't remove outliers because are not error/noise but companies with higher age. The boxplot shows that the age between the median and the maximum age is sparse.

# export aida.age 
aida.age <- aida.age[,c('Company.name','Age','Legal.form','ATECO.Sector.Name','Region','Year','Failed')]

save(aida.age, file="./dataset/aida.age.RData") # R binary format
#rm(aida.age)
```

Size
```{r}
# Il legislatore attribuisce la dimensione di un'azienda in base al totale degli elementi che costituiscono l'attivo dello stato patrimoniale, al risultato di esercizio ed al numero di dipendenti. Nel nostro caso abbiamo deciso di attribuire a size il totale delle attività dello stato patrimoniale
aida.size <- df

# We consider all the company without nan value
aida.size <- aida.size[!is.na(aida.size$Total.assetsth),]
summary(aida.size$Total.assetsth)
```

```{r}
# Anomaly detection

# Before outliers detection
boxplot(aida.size$Total.assetsth)
plot(density(aida.size$Total.assetsth))

# Size Anomaly Detection: iqr range approach
iqr <- IQR(aida.size$Total.assetsth)
q1 <- quantile(aida.size$Total.assetsth,0.25)
q3 <- quantile(aida.size$Total.assetsth,0.75)
lower.whisker <- q1 - 1.5*iqr
upper.whisker <- q3 + 1.5*iqr

outliers <- aida.size[aida.size$Total.assetsth < lower.whisker | aida.size$Total.assetsth > upper.whisker,'Total.assetsth']
nrow(outliers)/nrow(aida.size)

# Remove all outliers not between [q1-1.5*iqr,q3+1.5*iqr] (external from two whiskers)
aida.size <- aida.size[aida.size$Total.assetsth >= lower.whisker & aida.size$Total.assetsth <= upper.whisker,]

#After outliers detection
boxplot(aida.size$Total.assetsth)
plot(density(aida.size$Total.assetsth))

# export aida.size 
aida.size <- aida.size[,c('Company.name','Total.assetsth','Legal.form','ATECO.Sector.Name','Region','Year','Failed')]

save(aida.size, file="./dataset/aida.size.RData") # R binary format
#rm(aida.size)
```


```{r}
# Boxplot age
ggplot( data=aida.age, color ='red',aes(x=Age)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
  theme_ipsum() +
  theme(
    legend.position="none",
    plot.title = element_text(size=11)
  ) +
  ggtitle("Age boxplot") +
  xlab("")

# Boxplot size
ggplot( data=aida.size, color ='red',aes(x=Total.assetsth)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
  theme_ipsum() +
  theme(
    legend.position="none",
    plot.title = element_text(size=11)
  ) +
  ggtitle("Size boxplot") +
  xlab("")

summary(aida.age$Age)
summary(aida.size$Total.assetsth)
```

ROI: Return on Investments
```{r}
# Take all that companies which report ROI of last available year. Obviously all missing values are been deleted. The dataset is composed by 735.268 companies (39.20%)
aida.roi <- df

# We consider all the company without nan value
aida.roi <- aida.roi[!is.na(aida.roi$ROI),]
summary(aida.roi$ROI)
```

```{r}
# ROI Anomaly Detection: iqr range approach
iqr <- IQR(aida.roi$ROI)
q1 <- quantile(aida.roi$ROI,0.25)
q3 <- quantile(aida.roi$ROI,0.75)
lower.whisker <- q1 - 1.5*iqr
upper.whisker <- q3 + 1.5*iqr

# export aida.roi 
aida.roi <- aida.roi[,c('Company.name','ROI','Legal.form','ATECO.Sector.Name','Region','Year','Failed')]
skim(aida.roi)
#save(aida.roi, file="./dataset/aida.roi.RData") # R binary format
```
