---
title: "Question A"
output: html_notebook
---

Setup
```{r}
library(skimr)  
library(ggplot2)
library(hrbrthemes)   
library(forcats)  

# clean all
rm(list=ls())

# working dir
wdir_fg = "/Users/francescogemignani/Google Drive/SMD/_Risk-of-business-failure/git"
wdir_ff = "C:/Users/falle/OneDrive - University of Pisa/Data Science/Statistical Methods for Data Science/smdproject2021"
wdir_sc = "/Users/samuele/University/2.SMD/Risk-of-Business-Failure"
setwd(wdir_fg)
```


#####
#Age#
#####

Import & Summary
```{r}
# import aida dataset
load("./dataset/age_df.RData") # reload energy dataset

#summary
skim(age.df)

#dataset
head(age.df)
```
Histogram
```{r}
ggplot(data = age.df) + 
  geom_histogram(mapping=aes(x=Age, fill=Failed),binwidth = 2,color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080"))+
    theme_ipsum() +
    labs(fill='Failed')
```


######
#Size#
######

Import & Summary
```{r}
# import aida dataset
load("./dataset/size_df.RData") # reload energy dataset

#summary
skim(size.df)

#dataset
head(size.df)
```
Size Density
```{r}
# ggplot2 size plots

ggplot( data=size.df, aes(x=Total.assetsth.EURLast.avail..yr) ) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8)

ggplot(data=size.df, aes(x=Total.assetsth.EURLast.avail..yr, group=Failed, fill=Failed)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
```



#####
#ROI#
#####

Import & Summary
```{r}
# import aida dataset
load("./dataset/roi_df.RData") # reload energy dataset

#summary
skim(roi.df)

#dataset
head(roi.df)
```

ROI Histogram
```{r}
ggplot(data = roi.df) + 
  geom_histogram(mapping=aes(x=avg.roi, fill=Failed),binwidth = 1,color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080"))+
    theme_ipsum() +
    labs(fill='Failed')
```




##########
#SOLVENCY#
##########

Import & Summary
```{r}
# import aida dataset
load("./dataset/solvency_df.RData") # reload energy dataset

#summary
skim(solvency.df)

#dataset
head(solvency.df)
```

Solvency Histogram
```{r}
ggplot(data = solvency.df) + 
  geom_histogram(mapping=aes(x=avg.solvency, fill=Failed),binwidth = 2,color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080"))+
    theme_ipsum() +
    labs(fill='Failed')
```


